** δοςα - /opinio/ - opinia

*** Eleaci
- δοςα - błąd

*** Parminedes
Stanowisko elleatów stara się w jakimś stopniu zlagodzić Parmenides, który próbuje podzielić doksa na 2 części czy mówiąc lepiej - nadać doksa 2 formy. Otóż doksę rozumianą literalnie i doksę jako takiego rodzaju opinię czy mniemanie, które zasługuje na przyjęcie. Parmenides w ten sposób próbuje czy chce umiescić doksę na płaszczyźnie rozumu, ale też poniekąd trafia kulą w płot, ponieważ niszczy doksę jako taką, czyli doksę jako pewnego rodzaju postrzeganie świata poprzez zachodzące w tym świecie zjawiska, czyli to, co jest potrzebne naszej percepcji zmysłowej. Co do zmysłowego pojmowania, można by się odwołać do Melissosa, który uznaje doksę za rodzaj iluzji. Czyli właśnie za złudzenie zmysłowe.  Interpretacja jest prosta - jeśli coś jest złudzeniem, to jest wyłącznie złudzeniem, więc udział takiego złudzenia w świecie prawdy, rzeczywistym, a więc udział doksa w bycie - w tym co jest jest niewielki, a właściwie żaden. W pewnej mierze to istnienie doksa udaje się uzasadnić Platonowi, ale tylko w taki sposób, w jaki ocala on stawanie się. Uważa to stawanie się za coś, co jest pośrodku, pomiędzy bytem a nicością. U Platona pomiędzy rozumem a doświadczeniem (??) wyrożnia 2 poziomy rzeczywistości, wiąże doksa ze stawaniem się, które samo w sobie jest niejasne, wiec sama doksa staje się czymś niejasnym. Platon rozważając to pojecie mówi, że doksa to właściwie coś,co znajduje się pośrodku między wiedzą a ignorancją. Siłą rzeczy to coś nieokreślonego. Ale nie spełnia on też czegoś, co moglibyśmy ocenić kryterium wiedzy, wiec Platon zostawia nas z ręką w nocniku, bo on sam nie wie, z czym się wiąże doksa, czym ona jest.

*** Melissos
- δοςα - złudzenie zmysłowe
- udział δοςα w bycie jest niewielkie

*** Platon
- δοςα - stawanie sie, pomiędzy bytem a nicością
- zachodzi rozdźwięk pomiędzy rozumem a doświadczeniem
- coś, co znajduje się pomiędzy wiedzą a ignorancją (wrt zmiany czy wartości wiedzowej?)


*** Arystoteles
- przyznaje przewagę wiedzy nad δοςα


*** Sekstus Empiryk


*** Sceptycy
- δοςα, /opinio/ przeciwstawiają spekulacjom
- δοςα to nasze stanowisko co do tego jak świat jest, jak działa


** εμπειρισ - /experientia/ - doświadczenie


   
** παθος
- w παθος filozofia grecka widzi namiętności jako rzeczy do ograniczania, powsćiągliwości
- παθος - jest w części duszy którą mamy wspólną ze zwierzętami
- παθος
   
*** Arystoteles
- 
- παθος - gwałtowne wzburzenie jakiego zaznaje dusza (jej pożądliwa część) człowieka - namiętność

*** Stoicy
- apatia - usunięcię namiętności, namiętnosć jako następstwo błędnego sądu naszego rozumu


** δυναμις - /potentia/ - możność, możliwość

*** Arystoteles
- zasada ruchu lub zmiany w czymś drugim - "Sztuka budowania jest taką dynamis, która nie wystepuje w czymś, co jest budowane"
- zasada ruchu lub zmiany w czymś drugim (zmiana powodowana przez coś drugiego w czymś drugim)
- inercja(?)
- potencjał czegoś, istniejąca mozliwość zrobienia czegoś, zdolnosć do zrobienia czegos, np zdolność do wybudowania domu(nie oznacza że dom został, jest luv=b zostanie wybudowany)


*** Neoplatonicy
- dynamis - działanie, które ma charakter absolutnie nieskończony
