#+TITLE:Raymod Geuss - Philosophy and real politics


* Przedmowa

Książka jest rozwinnięciem lektury z Aten 2007


* Wstęp

***  "łagodna" interpretacja stwierdzenia "polityka to etyka w praktyce/etyka stosowana" ("politics is applied ethics")

- zarówno formy aktywności politycznej jak i sposoby ich badania nie są i nie mogą być wolnym od twierdzeń wartościujących przedsięwzięciem, i w tym sensie są szeroko pojętą "etyczną" aktywnością.

- nie wszystkie sytuacje, w których wystepuje dylemat etyczny są sytuacjami politycznymi. Jednakże należy zwrócić uwage na fakt, że wiele niepolitycznych sytuacji etycznych ma mimo wszystko ważną cechę wspólną z sytuacjami politycznymi; tzn wiele zmiennych w tych sytuacjach jest losowa lub nieprzewidywalna.

- aktorzy (?) polityczni generalnie mają za cel pewną koncepcję 'dobra', działajac w granicach tego, co uważają za dopuszczalne

- ludzie są słabymi, łatwymi do rozproszenia i pełnymi konfliktów - przez to nie zawsze robią to, co uwazają za dopuszczalne (słuszne?). 

- nie można zrozumieć działania ludzkich aktorów politycznych bez wzięcia pod uwagę uczynionych przed lub w trakcie ocen etycznych

- w tym sensie jest to etyka stosowana mniej w ten sam sposób jak algebra stosowana, a bardziej jako próba przetrwania we wszyscy-na-jednego

- quasi-Kartezjańskie podejscie do życia (a w tym przypadku do jego politycznego aspektu) nie jest wskazane gdyż zakłada, poprzez uznanie poglądów, ocen i opinii za możliwe do całkowicie precyzyjnego, względem absolutnego punktu odniesienia umieszczenia, ich stałość, pewnośc ( w danym momencie ). Tego typu przedsiemwzięcie jest, z powodów wymienionych w poprzednich punktach, niemożliwe.

-  utrudnia je też brak konsekwencji w ludzkim działaniu. O ile większość ludzi, przynajmniej do pewnego stopnia, dopuszcza niekonsekwencje w swoim życiu, rzadko jest ona rozpoznawana jako ogólny  
